INSERT INTO USERS ( USER_ID, CREATED_BY,  CREATED_DATE, FIRSTNAME, LASTNAME, MODIFIED_BY, MODIFIED_DATE, PASSWORD, PSEUDO ) VALUES ( 1, 1, NOW(), 'Admin', 'System', 1, NOW(), 'admin', 'SA' );
INSERT INTO USERS ( USER_ID, CREATED_BY,  CREATED_DATE, FIRSTNAME, LASTNAME, MODIFIED_BY, MODIFIED_DATE, PASSWORD, PSEUDO ) VALUES ( 2, 1, NOW(), 'Peter', 'Xmas', 1, NOW(), 'Bacon', 'pnoel' );

--INSERT INTO PROJECT ( PROJECT_ID, AUTHOR_ID, DESCRIPTION, NAME ) VALUES ( NEXT VALUE FOR PROJECT_SEQ, 1, 'This is a big project', 'Story #1' );